### ISSUE TITLE
Promotion of apps that use your API

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#11]
This will benefit both your API and Apps gain popularity ! 

:smile: 

Something like

## The API is used by following projects

[GurbaniNow](https://gurbaninow.com/web/) | [SikhJS](https://bogas04.github.io/SikhJS/) | ... 
:--|:--|:--

**Comment by bogas04** [comment]
In return, I think you can design a badge saying "Powered by GurbaniNow"

**Comment by davchana** [comment]
@bogas04 @Sarabveer "powered by ... " as well as Showcase both will be appreciated

**Comment by sarabveer** [comment]
If you want to add, just make a new PR and add your app/website to the list in the README

https://github.com/GurbaniNow/gurbaninow-api#used-by
