### ISSUE TITLE
[Suggestion] Gurlipi to Punjabi Unicode Route

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#14]
Add a new route that allows conversion between the two gurmukhi representations. This too can be helpful for several applications/bots.

# `/akhar` Representation Conversion 

**URL** - `akhar/:text/:target?`
**Examples** - `akhar/vwihgurU`
```json
{
  "error": false,
  "result": "ਵਾਹਿਗੁਰੂ",
  "target": "unicode"
}
```

Value | Description 
:--|:--
:text  | Text string passed by user for conversion
:target? | **OPTIONAL** <br />  `lipi` - Converts given unicode string to gurlipi text <br />  `unicode` - Converts given lipi string to unicode **(DEFAULT: unicode)**

**Comment by sarabveer** [comment]
We only have GurLipi -> Unicode

**Comment by sarabveer** [comment]
https://api.gurbaninow.com/akhar/%3C%3E

Will Add to API Docs
