### ISSUE TITLE
Add pagination support for search route

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#15]
Sites like STTM would need to skip and limit results for pagination.

Only skip variable needs to be added

`search/:query?skip=skip&results=results`

Variable | Use
:--|:--
`results`| Set count of results **(DEFAULT 20, MAX 100)** <br /> In case skip is set, this will return results from the `skip` to `skip+results` results.
`skip`| Skip records **(DEFAULT 0)** <br /> If you want 20 to 30 results, set skip=20 and results=10

SQL based DBs have `LIMIT 20, 10` or `LIMIT 20 OFFSET 10` sort of [syntax](https://stackoverflow.com/questions/2827029/mysql-skip-first-10-results) to do the same.

**Comment by sarabveer** [comment]
interesting, will implement
