### ISSUE TITLE
Hukamnama not updating

### ISSUE THREAD

**Issue by inderpreet99** [Sarabveer/gurbaninow#17]
It is currently 11:12 pm EST on July 20th. Today's (2017-07-21 IST) hukamnama endpoint [docs](https://github.com/GurbaniNow/gurbaninow-api#get-todays-hukamnama-from-darbar-sahib-amritsar) indicates the hukamnama updates at 9 pm EST. I don't see it being updated. Today's  hukamnama has already been updated on [sgpc.net](http://sgpc.net/daily-mukhwak-pdf/) (and sikhnet): ਤੁਮ ਦਾਤੇ ਠਾਕੁਰ ਪ੍ਰਤਿਪਾਲਕ ਨਾਇਕ ਖਸਮ ਹਮਾਰੇ ॥

Here's the current output from https://api.gurbaninow.com/v2/hukamnama/today

```
{
	"date": {
		"gregorian": {
			"month": "December",
			"date": 31,
			"year": 1969,
			"day": "Wednesday"
		},
		"nanakshahi": {
			"english": {
				"month": "Poh",
				"date": 18,
				"year": 501,
				"day": "Budhvaar"
			},
			"punjabi": {
				"month": "ਪੋਹ",
				"date": "੧੮",
				"year": "੫੦੧",
				"day": "ਬੁੱਧਵਾਰ"
			}
		}
	},
	"hukamnamainfo": null,
	"hukamnama": [],
	"license": "CC-BY-NC-ND-4.0"
}
```

**Comment by inderpreet99** [comment]
If I run https://github.com/KhalisFoundation/hukamnama-json, I get the correct hukamnama for today. Maybe this is just an issue of when that sync process runs during the day. Thanks.

**Comment by sarabveer** [comment]
We use SikhNet to get the Hukamnama, and they screwed up, I don't know what happened. This is normal though, this happend at least 5 times before.

I manually re-ran the script which automatically gets the Hukamnama around 12:30 AM EST and it was updated.

You can view the hukamnama here: https://gurbaninow.com/hukamnama

Thanks for notifying though!

**Comment by sarabveer** [comment]
> If I run https://github.com/KhalisFoundation/hukamnama-json, I get the correct hukamnama for today. Maybe this is just an issue of when that sync process runs during the day. Thanks.

That uses SGPC and isn't reliable as we have to guess the Hukamnama. We used to use this a few months ago, but then we switched to SikhNet.

SikhNet provides the actual ShabadID(s), so it is easier. Plus, if the hukamnama is multiple shabads, we support that too (Example: If the Hukamnama is from a Vaar, and you have the Saloks + Pauri)
