### ISSUE TITLE
Wrong Hukamnama Sahib!!!!

### ISSUE THREAD

**Issue by ErHarinderSingh** [Sarabveer/gurbaninow#18]
Hello Veerji, API ch hukamnama sahib galt aa reha hai....Ajj 1 Assu hai te otthe 2 assu show kr reha.. Naale Hukmnama Sahib v sahi ni aa reha.. Kirpa krke backend check kro.. Pehlan v bhut vaar sahi nahi aaya... 6 September da v wrong si..Ajj 16 September da v sahi nhi aya...
@bogas04 @Sarabveer Ji..

Check please : https://api.gurbaninow.com/v2/hukamnama/today

**Comment by sarabveer** [comment]
The Hukamnama for September 16, 2017 (Assu 2, 549 Nanakshahi 2003) is correct. I just checked the SGPC website.

**Comment by sarabveer** [comment]
BTW, For Future Reference: The GurbaniNow API uses the Original Nanakshahi Calendar passed by Sri Akal Takht in 2003

**Comment by ErHarinderSingh** [comment]
> The Hukamnama for September 16, 2017 (Assu 2, 549 Nanakshahi 2003) is correct. I just checked the SGPC website.

But 1 Assu Si ji,, Ajj 2 Assu hai.

**Comment by ErHarinderSingh** [comment]
Aaah dekho , 2 Aasu Ajj hai ji...
http://old.sgpc.net/hukumnama/sgpconlinehukamnama.asp

**Comment by sarabveer** [comment]
> BTW, For Future Reference: The GurbaniNow API uses the Original Nanakshahi Calendar passed by Sri Akal Takht in 2003

@ErHarinderSingh We use the Original Nanakshahi Calendar, in which today (Sunday, September 17th, 2017) is Aitvaar, 3 Assu, 549.

https://nanakshahi.sarabveer.me/

https://play.google.com/store/apps/details?id=com.ncal&hl=en
