### ISSUE TITLE
WriterID is 0 for first line in mode 2 (Shabad Search)

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#2]
`https://gurbaninow.com/api/?mode=2&shabadNo=123&format=json` gives WriterID=0 for the first line.

`"WriterID": "0", "English": "Siree Raag, Fourth Mehla:"`

This should not be the case, I think you will have to update the DB for this.

**Comment by sarabveer** [comment]
Yes, this is correct, because Mangals dont have a WriterID, will add though if you really need it.
