### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by visionthroughdesign** [Sarabveer/gurbaninow#20]
Is it possible to have a copy of the database published? or a repo of the structure?

**Comment by sarabveer** [comment]
Hello. What would this be used for?

**Comment by visionthroughdesign** [comment]
Require it for an offline version as some Gurdwara’s don’t have access to
internet.

So a locally hosted database to run against a light html app


On 19 October 2017 at 00:16:20, Sarabveer Singh (notifications@github.com)
wrote:

Hello. What would this be used for?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GurbaniNow/gurbaninow-api/issues/20#issuecomment-337743958>,
or mute the thread

**Comment by sarabveer** [comment]
Currently, a Desktop Program is in development. It will have the database encrypted.

Unlike other recent Programs in development, we are trying to program one using native languages instead of using heavy and bloated frameworks like Electron.
