### ISSUE TITLE
Page 1430 missing in guru granth sahib (raagmala)

### ISSUE THREAD

**Issue by mbaljeetsingh** [Sarabveer/gurbaninow#21]
While accessing the following URL, 
https://api.gurbaninow.com/v2/ang/1430, returned page array is empty, Can you add that?

**Comment by sarabveer** [comment]
[raagmala.json.zip](https://github.com/GurbaniNow/gurbaninow-api/files/1425518/raagmala.json.zip)

**Comment by mbaljeetsingh** [comment]
@Sarabveer  Just Noticed, Amrit Keertan is not working https://api.gurbaninow.com/v2/ang/1/A

**Comment by mbaljeetsingh** [comment]
Can't you add raagmala to api?

**Comment by sarabveer** [comment]
About the Amrit Keertan Issue: https://github.com/GurbaniNow/gurbaninow-api/issues/13

In APIv3, it will remove Amrit Keertan and have an Index of Shabads.

**Comment by mbaljeetsingh** [comment]
Ok, And when are you releasing APIv3?

**Comment by sarabveer** [comment]
Soon, a new Database from the ground up is being prepared for it.
