### ISSUE TITLE
hukumnama null for 2017/11/27 today

### ISSUE THREAD

**Issue by davchana** [Sarabveer/gurbaninow#22]
https://api.gurbaninow.com/v2/hukamnama/2017/11/26 for yesterday works, provides Hukumnama Sahib.
https://api.gurbaninow.com/v2/hukamnama/2017/11/27 gets redirected to https://api.gurbaninow.com/v2/hukamnama/today , normal, as expected.

https://api.gurbaninow.com/v2/hukamnama/today
provides:

```
{
	"date": {
		"gregorian": {
			"month": "November",
			"date": 27,
			"year": 2017,
			"day": "Monday"
		},
		"nanakshahi": {
			"english": {
				"month": "Maghar",
				"date": 14,
				"year": 549,
				"day": "Somvaar"
			},
			"punjabi": {
				"month": "ਮੱਘਰ",
				"date": "੧੪",
				"year": "੫੪੯",
				"day": "ਸੋਮਵਾਰ"
			}
		}
	},
	"hukamnamainfo": null,
	"hukamnama": [],
	"license": "CC-BY-NC-ND-4.0"
}
```

`	"hukamnamainfo": null,` is for all future dates, but 2017/11/27 is today; & Hukumnama Sahib has been issued from Darbar Sahib, see http://hukamnamasahib.com/2017/11/hukamnama-siri-darbar-sahib-amritsar-date-27-november-2017-ang-512/

Why is api not providing the data? Could you please have a look?

**Comment by sarabveer** [comment]
Odd. I am really busy at the moment, will look at it later.

November 28th Hukamnama is up, BTW.

**Comment by davchana** [comment]
Yes, thanks, 28th is up. Even reddit bot too didn't post for 27th, as well as GurbaniNow website also just continues loading for same date.

What is your source for Hukumnama? Maybe that failed?

**Comment by sarabveer** [comment]
Source for Hukamnama is SikhNet. Its really odd, need to look into it.

**Comment by sarabveer** [comment]
I have stopped web scraping SikhNet and now use their internal API endpoints to fetch the Hukamnama and Hukamnama Archives, the issue should be fixed.

**Comment by sarabveer** [comment]
https://api.gurbaninow.com/v2/hukamnama/2017/11/27

This works now.
