### ISSUE TITLE
Enhancement: Give error when hukamnama is not available for endpoint /year/month/day future dates

### ISSUE THREAD

**Issue by davchana** [Sarabveer/gurbaninow#24]
As of now, on 09th December, if I make a call to `https://api.gurbaninow.com/v2/hukamnama/2017/12/10` i.e.10th December, (or any future date for which hukamnama has not been issued yet), api will show only the last available hukamnama i.e.for today 09th December. If unavailable, it should give error in hukamnamainfo object.

**Comment by sarabveer** [comment]
Looks like SikhNet is doing this. Ill add checks to make sure the Hukamnama is for the day that the client is asking.

**Comment by davchana** [comment]
@Sarabveer I appreciate your work on this
