### ISSUE TITLE
Feature Request - Daily Prayers Section

### ISSUE THREAD

**Issue by visionthroughdesign** [Sarabveer/gurbaninow#27]
Hi, Is it possible to introduce a daily prayers section consisting of the following baniyan? 

- Japji Sahib
- Jaap Sahib
- Tav Prasad Svaiye 
- Rehras
- Kirtan Sohaila
- Ardaas (if available)

**Comment by sarabveer** [comment]
It is possible and it is currently being implemented in the next major release of the API (version 3).

The whole Sundar Gutka will be added.

**Comment by bhajneet** [comment]
These should be available now to preview/test: https://dev.gurbaninow.com/gutka
