### ISSUE TITLE
Database Work

### ISSUE THREAD

**Issue by sarabveer** [Sarabveer/gurbaninow#29]
https://github.com/ShabadOS/database

### Main
- [x] Import SGGS DB
- [x] Import Sri Dasam Granth
- [x] Import Bhai Gurdas Ji
- [x] Import Bhai Nand Lal Ji
- [ ] Import Sarabloh Granth Baani
- [x] Corrections to SGGS DB
- [x] Corrections to Sri Dasam Granth DB
- [x] Corrections Bhai Gurdas Ji DB
- [ ] Corrections to Bhai Nand Lal Ji DB
- [ ] Corrections to Sarabloh Granth Baani

### Vishrams
- [x] Import Vishrams (SGGS Ji)
- [x] Corrections to Vishrams (SGGS Ji)
- [x] Import Vishrams (Sri Dasam Granth)
- [ ] Corrections to Vishrams (Sri Dasam Granth)
- [x] Import Vishrams (Bhai Gurdaas Ji)
- [ ] Import Vishraams (Bhai Nand Lal)

### Indexes
- [x] Import Sundar Gutka Index (#27)
- [x] Import Writer Index
- [x] Import Secton Index
- [x] Import SubSection Index
- [ ] Add SubSection ID's to Panktee's
- [ ] Import Amrit Keertan Index
- [ ] Link Shabads with Amrit Keertan Index

### Translations
- [x] Import Sant Singh Khalsa English Translation
- [x] Import Prof. Sahib Singh Teeka with Arths and Notes
- [x] Import Fareedkot Teeka
- [x] Import Bhai Manmohan Singh's Punjabi and English Translations
- [x] Import Spanish Translations
- ~~[ ] Import Giani Harbans Singh Teeka~~

### Others
- [x] Get Unicode Conversion Scripts Working
- [x] Get Hindi Transliteration Scripts Working
- [x] Get English Transliteration Scripts Working
- [ ] Import GurmatBibek Ucharan PDF's

**Comment by Sarabveer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Database Work](https://trello.com/c/qruQMmjx/2-database-work)

**Comment by sarabveer** [comment]
Closed in favor of:

https://github.com/ShabadOS/database/issues/847

https://github.com/ShabadOS/database/issues/846
