### ISSUE TITLE
Minor; Hukumnama for today 23/05/2018 does not load

### ISSUE THREAD

**Issue by davchana** [Sarabveer/gurbaninow#33]
Hukumnama for 23/05 today is just redirecting to 22/05, which goes to /today endpoint.

Almost similar issue was https://github.com/GurbaniNow/api/issues/22

Gurbaninow.com is also showing hukum for yesterday 22nd only, instead of today's 23rd.

Sikhnet shows correct date, 23rd today.

Current time 6pm IST.

**Comment by sarabveer** [comment]
I manually re-ran the script. Looks like SikhNet didn't update at 9PM EST or at 12AM EST.
