### ISSUE TITLE
Incomplete Sri Guru Granth Sahib Ji (1430)

### ISSUE THREAD

**Issue by sukhpreet011** [Sarabveer/gurbaninow#35]
Dear Sir/Madam,
We all know that there are 1430 ang in shri guru granth sahib ji.
But when i use your api, i cant find and 1430.
Moreover the 1429 ang is incomplete.

Please check and revert.
Regards,
Sukhpreet Singh

**Comment by sarabveer** [comment]
Will be fixed when the API starts using the new @ShabadOS Database.
