### ISSUE TITLE
Mistake in Bhai Gurdaas Ji Vaar 1, Pauri 23

### ISSUE THREAD

**Issue by manshantsingh** [Sarabveer/gurbaninow#36]
Not sure where I am supposed to report them so I am reporting it here instead. 

https://gurbaninow.com/shabad/5563/

First pankti of the shabad, last word should be ਪਠਾਇਆ

**Comment by sarabveer** [comment]
I had caught this issue before as well.

https://github.com/ShabadOS/database/blob/master/data/Vaaran%20Bhai%20Gurdas%20Ji/01.json#L4305

It has been corrected in the Shabad OS database, it will be corrected in GurbaniNow once it ports over to the new DB
