### ISSUE TITLE
Inconsistent Data Type for startang and endang

### ISSUE THREAD

**Issue by singhparveen** [Sarabveer/gurbaninow#37]
I'm trying to pull results/search  by ANG.
While doing to "G"(Guru Granth Saheb), under 'RAAG' type, it gives

```
"raag": {
"id": 1,
"akhar": "jpu",
"unicode": "ਜਪੁ",
"english": "Jap",
"startang": 1,
"endang": 8,
"raagwithpage": "Jap (1-8)"
},
```

while during "D" (Dasam Granth), it gives

```
"raag": {
"id": 48,
"akhar": "jwpu",
"unicode": "ਜਾਪੁ",
"english": "Jaap",
"startang": "",
"endang": "",
"raagwithpage": ""
},
```
key "startang" and "endang" have both string and int types. I was facing issue while pulling data by serilaization as it works with non-dynamic types and wanted to see if there's any possible fix for it.
Thanks

**Comment by sarabveer** [comment]
Thanks for submitting this.

I am currently in the process of re-writing the API to use a newer database. It should be fixed with the new version.

**Comment by singhparveen** [comment]
Thanks
