### ISSUE TITLE
Improve API routes

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#4]
It's very crude right now. You can try a cleaner scheme, something like:

mode=1 becomes `/search/:query?source_id=(0|1|2|3)&type=(0|1|2|3)...`
mode=2 becomes `/shabad/:shabad_id`
mode=3 becomes `/ang/:ang_id?source_id=(0|1|2|3)`

Keeping format=json, writer -> writer_id=0, recnum -> count=10, raag -> raag_id=0 as defaults to clean up the route a bit. Also renaming them to match the response of API.

Also using camelCase or snake_case as one standard throughout API (route and response) would be nice.

**Comment by sarabveer** [comment]
Yea, thinking about this, need to learn how to implement with PHP though.

**Comment by bogas04** [comment]
You can use SLIM framework http://www.slimframework.com

**Comment by sarabveer** [comment]
I'm removing XML Support, as its not used and hard to maintain.

**Comment by tjgurwara99** [comment]
@Sarabveer which database are you using? Maybe I can help you write this in Python Django REST framework. Let me know if you wanna collab😄
