### ISSUE TITLE
SourceID in response is not numerical

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#5]
https://gurbaninow.com/api/?mode=2&shabadNo=7616&format=json

SourceID is "D" here instead of 3 as per [Search API](https://github.com/Sarabveer/gurbaninow/blob/master/API.md#search)

It'll be great if you make it consistent throughout the API.

**Comment by sarabveer** [comment]
Results are not same as API, I will add a section to the Doc about the result

**Comment by bogas04** [comment]
It'll be better if API could accept A B D G instead of 0 1 2 3 or something like that, to keep everything consistent

**Comment by sarabveer** [comment]
There are more:

A - Amrit Keertan
B - Gurdas Ji Vaaran
G - Guru Granth Sahib
D - Dasam Granth
N - Nand Lal Ji Vaaran
U - Uggardanti
