### ISSUE TITLE
Add bounds of ids and pages to API document

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#8]
This helps in validating at client side. So it'll be great if you could add limits like 1-1430 for SGGS and so on

**Comment by bogas04** [comment]
http://api.sikher.com/page/12356 check this for example.

**Comment by sarabveer** [comment]
doesn't `count``0` already serve this purpose?
https://api.gurbaninow.com/ang/1431

**Comment by bogas04** [comment]
I think you don't understand the point of it. I'm asking you to alter API such that whenever an ang that isn't present is requested, you respond saying that there are no more angs & that there are only 1-1430 angs. 

That is more helpful as an API and lets developer sort of know the bounds of ang without testing every each ang or manually reading the docs. This would graciously break the application and also letting the developer know why it broke and how to fix it. Much more informative than count:0

**Comment by sarabveer** [comment]
Ill specify in the docs, and ill add to error if there is no ang for the specific source.

**Comment by Sarabveer** [comment]
https://api.gurbaninow.com/ang/1431

Added, will add soon for dasam granth and other sources, as thier ang numbers are bit weird.

**Comment by bogas04** [comment]
Wait, where's 1430 ?
