### ISSUE TITLE
Let user decide what fields shall be present in the response

### ISSUE THREAD

**Issue by bogas04** [Sarabveer/gurbaninow#9]
This will improve response time of the API as the responses would be tailored to user's requirement.

**Comment by sarabveer** [comment]
Only the `:query` is required, if you need to specifiy something specific then you use the additional options.

**Comment by bogas04** [comment]
I think you misunderstood the point.

Say I only want lineno & Gurmukhi for any route, then API could accept some more params to trim response based on the fields asked by the user. This will help small and large applications to spend less time on HTTP requests. 

Something like

`/shabad/123?only=lineno,gurmukhi`
this gives only gurmukhi and lineno in response 

`/shabad/123?ignore=shabadid,gurmukhi`
this gives everything except shabadid & gurmukhi

**Comment by sarabveer** [comment]
In the modern world, reducing that much data wont do much. My API is behind cloudflare which caches the results in its CDNs all over the world.

**Comment by bogas04** [comment]
It does matter when you have a lot of requests, in cases like search or angs with a lot of lines.

> For example search results page would only want to show gurmukhi and english translation.

Do remember that third world countries still have 2G as their average speed and it too is flaky at times.

**Comment by sarabveer** [comment]
My API is behind cloudflare which caches the results in its CDNs all over the world. The requests don't directly come  from my server in New York City.

**Comment by bogas04** [comment]
That only solves the load on server and not on client.

Note that data is one part (might not be an issue for `west`), but processing that data is also an issue. Cheap-ass android phones with slow browsers still need to deal with arrays of huge strings.

I insist to re-consider `only` & `ignore` params, not to be implemented immediately but at least in future.

**Comment by Sarabveer** [comment]
In the future yes, But damn, I tested GurbaniNow on the cheapest phone available, it even worked on that $4 phone from India

**Comment by sarabveer** [comment]
Continued on #19
