### ISSUE TITLE
Daily Hukamnama not updating at the mentioned time

### ISSUE THREAD

**Issue by sukhpreet011** [Sarabveer/gurbaninow#95]
Dear Team,

I have noticed that from past few days the daily hukamnama is not updating at the mentioned time i.e.  9:00 PM Eastern Time (IST 6:30 AM).

Please check.

**Comment by sarabveer** [comment]
The Hukamnama has 2 times to update. If the hukamnama doesn't update at 9PM EST, it will update 12AM EST.

Check the readme file.
